import java.util.ArrayList;
import java.util.Iterator;
import java.util.Scanner;
public class WeeklyTempForcast {
    public static void WeeklyTempForecast (Strings[] args) {
        //Initialize ArrayLists to store Days and Temps
        ArrayList<String> days = new ArrayList<>();
        ArrayList<Double> temps = new ArrayList<>();

        //Pre-Populate ArrayLists
        String [] weekDays = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
        double [] weeksTemps = {"92.2", "94.1", "82.5", "82.0", "88.0", "94.4", "93.5"};
    }
}